name = "qrlinalg"
version = "0.1.0"
license = "GPL-3.0-or-later"

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[library]
source-dir = "src"

[preprocess.cpp]
suffixes = ["f", "f90"]
directories = ["src"]
macros = ["QRLINALG_WP=8"]
